### ISSUE TITLE
Repo contains OS X DS_Store files

### ISSUE THREAD

**Issue by tallzilla** [zerowriter/zerowriter1#7]
I love this project, I've been playing around with this for several hours and look forward to the v2 waveshare drivers.

One small nit - this repo contains .DS_Store and ._.DS_Store files in each directory, presumably written by the OS X filesystem you're working on (this happens to me all the time). If you add these to a global .gitignore file they won't be passed on for everyone to see.

This will add a global ignore to your local projects
git config --global core.excludesfile "~/.gitignore" &&  echo *.DS_Store >> ~/.gitignore

Thanks!

**Comment by tallzilla** [comment]
Actually the above gist just future-proofs your code. You'll need to run this from your project's root directory to remove the existing DS_Store files in the project:

find . -name .DS_Store -print0 | xargs -0 git rm --ignore-unmatch

**Comment by zerowriter** [comment]
Thanks! I will add this. I frequently work between OSX, linux, and PC so -- kind of all over the place.
